name: Security

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "Definitions/**"
      - ".github/workflows/**"

permissions:
  contents: read
  id-token: write

jobs:
  # plan:
  #   name: Plan
  #   uses: ./.github/workflows/tpl-plan.yml
  #   if: github.event_name == 'workflow_dispatch'
  #   with:
  #     pacEnvironmentSelector: Security-Prod
  #   secrets: inherit

  get_artifact:
    name: Plans
    uses: ./.github/workflows/tpl-get-artifact.yml
    if: github.event.pull_request.merged == true
    with:
      pr-workflow: pr-plan-sec.yml
      pacEnvironmentSelector: Security-Prod

  policies:
    name: Policy Changes
    uses: ./.github/workflows/tpl-deploy-policy.yml
    needs:
      - get_artifact
    if: needs.get_artifact.outputs.deployPolicyChanges == 'yes'
    with:
      pacEnvironmentSelector: Security-Prod
      planRunId: ${{ needs.get_artifact.outputs.planRunId }}
    secrets: inherit

  roles:
    name: Role Changes
    uses: ./.github/workflows/tpl-deploy-roles.yml
    needs:
      - get_artifact
      - policies
    if: ${{ ! failure() && ! cancelled() && needs.get_artifact.outputs.deployRoleChanges == 'yes' }}
    with:
      pacEnvironmentSelector: Security-Prod
      planRunId: ${{ needs.get_artifact.outputs.planRunId }}
    secrets: inherit
