# This pipeline is used to plan exemptions in a pull request
name: Landing Zone Exemptions

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - "Definitions/policyExemptions/**"
      - ".github/workflows/**"

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

permissions:
  actions: read
  checks: read
  contents: read
  id-token: write

jobs:
  plan:
    name: Plans
    uses: ./.github/workflows/tpl-plan-exemptions-only.yml
    if: github.event_name == 'workflow_dispatch'
    with:
      pacEnvironmentSelector: LandingZone-Prod
    secrets: inherit

  get_artifact:
    name: Plans
    uses: ./.github/workflows/tpl-get-artifact.yml
    if: github.event.pull_request.merged == true
    with:
      pr-workflow: pr-exemptions-lz.yml
      pacEnvironmentSelector: LandingZone-Prod

  exemptions:
    name: Deploy
    uses: ./.github/workflows/tpl-plan-exemptions-only.yml
    needs:
      - plan
      - get_artifact
    if: >
      ${{
        always()
        && (
          needs.plan.result == 'success'
          || needs.get_artifact.result == 'success'
        )
        && (
          needs.plan.outputs.deployPolicyChanges == 'yes'
          || needs.get_artifact.outputs.deployPolicyChanges == 'yes'
        )
      }}
    with:
      pacEnvironmentSelector: LandingZone-Prod
    secrets: inherit
