name: Security

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - Definitions/**
      - .github/workflows/**

permissions:
  actions: read
  checks: read
  contents: read
  id-token: write

jobs:
  plan:
    name: Plans
    uses: ./.github/workflows/tpl-plan.yml
    if: github.event_name == 'workflow_dispatch'
    with:
      pacEnvironmentSelector: Security-Prod
    secrets: inherit

  get_artifact:
    name: Plans
    uses: ./.github/workflows/tpl-get-artifact.yml
    if: github.event.pull_request.merged == true
    with:
      pr-workflow: pr-plan-sec.yml
      pacEnvironmentSelector: Security-Prod

  policies:
    name: Policy Changes
    uses: ./.github/workflows/tpl-deploy-policy.yml
    needs:
      - plan
      - get_artifact
    if: >
      ${{
        always()
        && (
          needs.plan.result == 'success'
          || needs.get_artifact.result == 'success'
        )
        && (
          needs.plan.outputs.deployPolicyChanges == 'yes'
          || needs.get_artifact.outputs.deployPolicyChanges == 'yes'
        )
      }}
    with:
      pacEnvironmentSelector: Security-Prod
    secrets: inherit

  roles:
    name: Role Changes
    uses: ./.github/workflows/tpl-deploy-roles.yml
    needs:
      - plan
      - get_artifact
      - policies
    if: >
      ${{
        always()
        && (
          needs.policies.result == 'success'
          || needs.policies.result == 'skipped'
        )
        && (
          needs.plan.result == 'success'
          || needs.get_artifact.result == 'success'
        )
        && (
          needs.plan.outputs.deployRoleChanges == 'yes'
          || needs.get_artifact.outputs.deployRoleChanges == 'yes'
        )
      }}
    with:
      pacEnvironmentSelector: Security-Prod
    secrets: inherit
