name: Generate Documentation

on:
  schedule:
    - cron: "24 20 * * *"
  workflow_run:
    workflows:
      - Deploy Policy Changes
    types:
      - completed
  workflow_dispatch:

concurrency:
  group: wiki
  cancel-in-progress: true

permissions:
  contents: write
  id-token: write

jobs:
  generate:
    name: Document Policies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout EPAC
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}
          path: ${{github.repository}}

      - name: Checkout Wiki
        uses: actions/checkout@v4
        with:
          repository: ${{github.repository}}.wiki
          path: ${{github.repository}}.wiki

      - name: Install Required Modules
        uses: azure/powershell@v2
        with:
          inlineScript: |
            Install-Module EnterprisePolicyAsCode -Force
            Install-Module Az.ResourceGraph -Force
          azPSVersion: latest

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          enable-AzPSSession: true
          allow-no-subscriptions: true

      - name: Build Documentation
        id: build-docs
        uses: azure/powershell@v2
        with:
          inlineScript: |
            Set-Location (Join-Path $env:GITHUB_WORKSPACE '${{github.repository}}')
            Build-PolicyDocumentation -PacSelector LandingZone-Prod `
              -OutputFolder (Join-Path $env:GITHUB_WORKSPACE '${{github.repository}}.wiki/policy-documentation')
          azPSVersion: latest

      - name: Publish to Wiki
        working-directory: ${{github.repository}}.wiki
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Update EPAC documentation" && git push
