# This pipeline is used to plan production deployment, and validate development
# deployment of Policies, Initiative definitions and Assignments into Azure.
name: Landing Zone Prod

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
    paths:
      - "Definitions/**"
      - ".github/workflows/**"

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan
    uses: ./.github/workflows/tpl-plan.yml
    with:
      pacEnvironmentSelector: LandingZone-Prod
    secrets: inherit
