name: Sync Upstream Policies
on:
  workflow_dispatch:
  schedule:
    - cron: "37 14 15 * *"

permissions:
  contents: read
  id-token: write

jobs:
  alz:
    name: ALZ Policies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        shell: pwsh
    env:
      PAC_DEFINITIONS_FOLDER: ./Definitions
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/heads/alz-policies

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get Latest Release
        id: latest
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Getting latest Enterprise Scale release');
            const latest = await github.rest.repos.getLatestRelease({
              owner: 'Azure',
              repo: 'Enterprise-Scale',
            });
            const latestTag = latest.data.tag_name;
            console.log(`Latest ALZ policies date: ${latestTag}`);
            core.setOutput('latest', latestTag);

      - name: Get Current Release
        id: current
        env:
          LatestTag: ${{ steps.latest.outputs.latest }}
        run: |
          $Current = Get-Content -Path './policy-versions.json'
                   | ConvertFrom-Json
                   | Select-Object -ExpandProperty alz
          Write-Host "Current policies date: $Current"
          Write-Host "CurrentTag=$Current" >> $env:GITHUB_OUTPUT

          # Determine if the latest release is newer than the current release
          if ([DateTime]$env:LatestTag -gt [DateTime]$Current) {
            Write-Host 'New version available'
            'UpdatePolicies=true' | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          } else {
            Write-Host 'No new version'
            'UpdatePolicies=false' | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          }

      - name: Update to Latest ALZ Policies
        id: update
        if: >
          steps.current.outcome == 'success' && fromJSON(steps.current.outputs.UpdatePolicies)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          Latest: ${{ steps.latest.outputs.latest }}
        run: ./Scripts/Update-AlzPolicies.ps1 -ReleaseTag $env:Latest

      - name: Create Pull Request
        uses: actions/github-script@v7
        if: >
          steps.update.outcome == 'success' && fromJSON(steps.update.outputs.PolicyUpdates)
        env:
          latest: ${{ steps.latest.outputs.latest }}
        with:
          script: |
            console.log('Looking for existing Pull Requests');
            const { repo, owner } = context.repo;
            const pulls = await github.rest.pulls.list({
              owner: owner,
              repo: repo,
              head: 'refs/heads/alz-policies',
              base: 'main',
              state: 'open',
            });
            console.log(`Found ${pulls.data.length} existing pull requests`);

            if (pulls.data.length < 1) {
              console.log('Creating Pull Request');
              await github.rest.pulls.create({
                owner: owner,
                repo: repo,
                head: 'refs/heads/alz-policies',
                base: 'main',
                title: `Update ALZ policies to ${process.env.latest} release`,
                body: `Updated to ${process.env.latest} release`,
              });
            } else {
              const existingPR = pulls.data[0];
              await github.rest.pulls.update({
                owner: owner,
                repo: repo,
                pull_number: existingPR.number,
                title: `Update ALZ policies to ${process.env.latest} release`,
                body: [
                  `Updated to ${process.env.latest} release`,
                  existingPR.body,
                ].join('\n\n'),
              });
            }

  amba:
    name: AMBA Policies
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    defaults:
      run:
        shell: pwsh
    env:
      PAC_DEFINITIONS_FOLDER: ./Definitions
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: refs/heads/amba-policies

      - name: Configure Git
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get Latest Commit Date
        id: latest
        uses: actions/github-script@v7
        with:
          script: |
            console.log('Getting latest AMBA commit date');
            const latest = await github.rest.repos.getCommit({
              owner: 'anwather',
              repo: 'amba-export',
              ref : 'main',
            });
            const commitDate = latest.data.commit.author.date.split('T')[0];
            console.log(`Latest ALZ policies date: ${commitDate}`);
            core.setOutput('latest', commitDate);

      - name: Get Current Release
        id: current
        env:
          Latest: ${{ steps.latest.outputs.latest }}
        run: |
          $Current = Get-Content -Path './policy-versions.json'
                   | ConvertFrom-Json
                   | Select-Object -ExpandProperty amba
          Write-Host "Current policies date: $Current"
          Write-Host "CurrentTag=$Current" >> $env:GITHUB_OUTPUT

          # Determine if the latest release is newer than the current release
          if ([DateTime]$env:Latest -gt [DateTime]$Current) {
            Write-Host 'New version available'
            'UpdatePolicies=true' | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          } else {
            Write-Host 'No new version'
            'UpdatePolicies=false' | Out-File -FilePath $env:GITHUB_OUTPUT -Encoding utf8 -Append
          }

      - name: Update to Latest Policies
        id: update
        if: >
          steps.current.outcome == 'success' && fromJSON(steps.current.outputs.UpdatePolicies)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./Scripts/Update-AmbaPolicies.ps1 -ReleaseDate ${{ steps.latest.outputs.latest }}

      - name: Create Pull Request
        uses: actions/github-script@v7
        if: >
          steps.update.outcome == 'success' && fromJSON(steps.update.outputs.PolicyUpdates)
        env:
          latest: ${{ steps.latest.outputs.latest }}
        with:
          script: |
            console.log('Looking for existing Pull Requests');
            const { repo, owner } = context.repo;
            const pulls = await github.rest.pulls.list({
              owner: owner,
              repo: repo,
              head: 'refs/heads/amba-policies',
              base: 'main',
              state: 'open',
            });
            console.log(`Found ${pulls.data.length} existing pull requests`);

            if (pulls.data.length < 1) {
              console.log('Creating Pull Request');
              await github.rest.pulls.create({
                owner: owner,
                repo: repo,
                head: 'refs/heads/amba-policies',
                base: 'main',
                title: `Update AMBA policies to ${process.env.latest} release`,
                body: `Updated to ${process.env.latest} release`,
              });
            } else {
              const existingPR = pulls.data[0];
              await github.rest.pulls.update({
                owner: owner,
                repo: repo,
                pull_number: existingPR.number,
                title: `Update AMBA policies to ${process.env.latest} release`,
                body: [
                  `Updated to ${process.env.latest} release`,
                  existingPR.body,
                ].join('\n\n'),
              });
            }
